onlinecourses/accounts/urls.py
from django.urls import path
from . views import *

app_name = 'accounts'

urlpatterns = [
    path('register', signup, name="signup"),
    path('user/activation',activation, name="activation"),
    path('test', activation, name='test'),
]

onlinecourses/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('courses/', include ('courses.urls')),
    path('api/v1/', include('api.v1.urls')),
]

onlinecourses/courses/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, CourseDeleteView, CourseCreateView, CourseUpdateView

urlpatterns = [
    path('list', CourseListView.as_view(), name="course_list"),
    path('create/', CourseCreateView.as_view(), name='create_course'),
    path('<slug:slug>/delete', CourseDeleteView.as_view(), name='delete_course'),
    path('<slug:slug>/update', CourseUpdateView.as_view(), name='update_course'),
    path('<slug:slug>/', CourseDetailView.as_view(), name='course_detail'),

]

onlinecourses/courses/models.py
import uuid
from django.db import models
from django.core.validators import validate_image_file_extension
from django.contrib.auth.models import User
from core.utils import generate_uuid_token


def upload_image_dir(instance, filename):
    return f'media/uploads/courses/{filename.lower()}'


class Course(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=150, unique=True)
    description = models.TextField(default="No description yet")
    slug = models.SlugField()
    image = models.ImageField(upload_to=upload_image_dir, blank=True, validators=[validate_image_file_extension])


    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title


class CourseEnrollment(models.Model):
    """
    Model to track course enrollments.
    """
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)


class CourseModule(models.Model):
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    name = models.CharField(max_length=128)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Section(models.Model):
    name = models.CharField(max_length=128)
    module = models.ManyToManyField(CourseModule, related_name='sections')

    def __str__(self):
        return self.name

class Unit(models.Model):
    """
    Course section unit to make it reusable
    """
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    content = models.TextField()

onlinecourses/courses/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView
from django.urls import reverse_lazy
from .models import Course


class CourseDetailView(DetailView):
    model = Course
    template_name = 'course_detail.html'


class CourseListView(ListView):
    model = Course
    template_name = 'course_list.html'


class CourseDeleteView(DeleteView):
    model = Course
    template_name = 'course_delete.html'
    success_url = reverse_lazy('course_list')


class CourseCreateView(CreateView):
    model = Course
    template_name = 'course_create.html'
    success_url = reverse_lazy('course_list')
    fields = ['title', 'description', 'slug']


class CourseUpdateView(UpdateView):
    model = Course
    template_name = 'course_update.html'
    success_url = reverse_lazy('course_list')
    fields = ['title', 'description']

onlinecourses/courses/templates/course_create.html
{% extends 'courses_base.html' %}

{% block content %}
	<h3>Create Course</h3>
    <form method="post">
    	{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>
{% endblock %}

onlinecourses/courses/templates/course_delete.html
{% extends 'courses_base.html' %}
{% block title %}Course deletion{{ course.title }}{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ course.title }}?</p>
        <input type="submit" value=Delete>
        <a href="{% url 'course_list' %}">Cancel</a>
    </form>
{% endblock %}

onlinecourses/courses/templates/course_detail.html
{% extends 'courses_base.html' %}

{% block content %}
    <h1>Title: {{ course.title }}</h1>
    <h3>Description: {{ course.description }}</h3>
    </h3>
    <h4>Modules</h4>
    <ul>
        {% for coursemodule in course.coursemodule_set.all %}
            <li>
                {{ coursemodule }}
            </li>
            {% for section in coursemodule.sections.all %}
            <li>
                {{ section }}
            </li>
            {% endfor%}
            {% empty %}
            <p>There are no modules in this course yet.</p>
        {% endfor %}
    </ul>
{% endblock %}

onlinecourses/courses/templates/course_list.html
{% extends 'courses_base.html' %}
{% block content %}
    <h1>Courses List</h1>
    <ul>
        {% for course in object_list %}
            <li>
                <a href="{% url 'course_detail' course.slug %}">{{ course.title }}</a>
                <a href="{% url 'update_course' course.slug %}">Edit</a> |
                <a href="{% url 'delete_course' course.slug %}">Delete</a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'create_course' %}">Create a new course</a>
{% endblock %}

onlinecourses/courses/templates/course_update.html
{% extends 'courses_base.html' %}

{% block content %}
	<h3>Edit Course</h3>
    <form method="post">
    	{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>
{% endblock %}

onlinecourses/courses/templates/courses_base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav>
    <ul>
        <li>
            <a href="{% url 'accounts:signup' %}">Signup</a>
        </li>
        <li>
            <a href="{% url 'accounts:test' %}">Test page</a>
        </li>
    </ul>
</nav>

<main>
    {% block content %}
    {% endblock %}
</main>
</body>
</html>